# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 자기소개
    url: /
    weight: 10
  - name: 코딩문제풀이
    url: /#papers
    weight: 11
  - name: 위치
    url: /#talks
    weight: 12
  - name: 근황
    url: /#news
    weight: 13
  - name: 경력
    url: experience/
    weight: 20
  - name: 프로젝트
    url: projects/
    weight: 30
  - parent: 프로젝트
    name: 학교 프로젝트
    url: school/
    weight: 40
  - parent: 프로젝트
    name: 외부 프로젝트
    url: national/
    weight: 50

  - name: 수업
    url: teaching/
    weight: 50
